### ISSUE TITLE
Update fms_mixedmode branch to dev/emc 20221017 version

### ISSUE THREAD

**Issue by binli2337** [NOAA-EMC/GFDL_atmos_cubed_sphere#78] opened 2022-11-03 14:00 UTC
The fms_mixedmode branch will be updated to include the latest changes from the dev/emc branch at NOAA-GFDL/GFDL_atmos_cubed_sphere (20221017 version or #aa42f6e).

**Comment by junwang-noaa** [comment] 2024-02-26 13:50
The code is committed to GFDL's repo. The issue is closed.

**Closed as completed by junwang-noaa** 2024-02-26 13:50 UTC
