### ISSUE TITLE
Update fms_mixedmode branch to include the latest changes from dev/emc of NOAA-GFDL/GFDL_atmos_cubed_sphere 

### ISSUE THREAD

**Issue by binli2337** [NOAA-EMC/GFDL_atmos_cubed_sphere#75] opened 2022-10-20 20:25 UTC
The fms_mixedmode branch will be updated to include the latest changes from the dev/emc branch at NOAA-GFDL/GFDL_atmos_cubed_sphere.

**Comment by junwang-noaa** [comment] 2024-02-26 13:51
The code is committed to GFDL's repo, the issue is closed.

**Closed as completed by junwang-noaa** 2024-02-26 13:51 UTC
